### ISSUE TITLE
[报告问题] ERROR Plugin load failed: hexo-url-submission

### ISSUE THREAD

**Issue by ousugo** [abnerwei/hexo-url-submission#19]
## Information 信息

**Version/版本:** 2.0.1

**Platform/操作系统:** Windows

**npm版本:** 11.0.0

**hexo版本:** 7.3.0

**科学上网方式:**

## Expected behaviour 预期行为
**答：** 安装插件后，成功运行插件，进行链接推送

## Actual behaviour 实际行为

**答：** 使用 `npm install --save hexo-url-submission` 安装完插件以后，运行 `hexo v` 就直接报下面的错误：
```
hexo v
INFO  Validating config
ERROR Plugin load failed: hexo-url-submission
Error: EISDIR: illegal operation on a directory, read
    at async readFileHandle (node:internal/fs/promises:554:24)
hexo: 7.3.0
hexo-cli: 4.3.2
os: win32 10.0.22631 undefined
node: 22.12.0
acorn: 8.14.0
ada: 2.9.2
amaro: 0.2.0
ares: 1.34.3
brotli: 1.1.0
cjs_module_lexer: 1.4.1
cldr: 46.0
icu: 76.1
llhttp: 9.2.1
modules: 127
napi: 9
nbytes: 0.1.1
ncrypto: 0.0.1
nghttp2: 1.64.0
nghttp3: 0.7.0
ngtcp2: 1.3.0
openssl: 3.0.15+quic
simdjson: 3.10.0
simdutf: 5.6.1
sqlite: 3.47.0
tz: 2024b
undici: 6.21.0
unicode: 16.0
uv: 1.49.1
uvwasi: 0.0.21
v8: 12.4.254.21-node.21
zlib: 1.3.0.1-motley-71660e1
```
![image](https://github.com/user-attachments/assets/b6ccd9a4-d4f6-4ce8-acfe-5c93fa49f397)

我是直接使用 google_key.json 文件的，json文件和 _config.yml 都放在项目根目录下
```
url_submission:
   enable: true
   type: 'latest' # latest or all( latest: modified pages; all: posts & pages)
   channels: # included channels are `baidu`, `google`, `bing`, `shenma`
     baidu:
       token: "xxxxxxxxxx" # Baidu Private Token
       count: 10 # Optional
     bing:
       token: "xxxxxxxxxxx" # Bing Access Token
       count: 10 # Optional
     google:
       key: "google_key.json" # Google key path (e.g. `google_key.json` or `data/google_key.json`)
       count: 10 # Optional
     shenma:
       count: 10 # Optional
       user: "" # Username used when registering
       token: "" # ShenMa Private Key
   prefix: ['/post', '/wiki'] # URL prefix
   ignore: ["/post/a*", "/post/a?c"] # URL addresses that do not need to be submitted (wildcards are supported)
   count: 10 # Submit limit
   urls_path: 'submit_url.txt' # URL list file path
   sitemap: 'sitemap.xml' # Sitemap path(e.g. the url is like this https://abnerwei.com/baidusitemap.xml, you can fill in `baidusitemap.xml`)
```
查看 `node_modules/hexo-url-submission` 文件夹，发现没有代码：
![image](https://github.com/user-attachments/assets/c8785068-dd6b-4ab6-ae38-77451bb84e97)

## Steps to reproduce the behaviour 重现步骤
**答：** 使用 `npm install --save hexo-url-submission` 安装完插件以后，运行 `hexo v`  或 `hexo g`

## Feature Request 功能方面的建议

**答：**

---
